//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPool.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarPoolRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCarPoolRegistration()
        {
            this.tblCarPoolMemberAssociations = new HashSet<tblCarPoolMemberAssociation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> PoolDate { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<double> Charges { get; set; }
        public Nullable<int> SeatsAvailable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCarPoolMemberAssociation> tblCarPoolMemberAssociations { get; set; }
    }
}
